basic.showString("9")
basic.pause(100)
basic.showString("8")
basic.pause(100)
basic.showString("7")
basic.pause(100)
basic.showString("6")
basic.pause(100)
basic.showString("5")
basic.pause(100)
basic.showString("4")
basic.pause(100)
basic.showString("3")
basic.pause(100)
basic.showString("2")
basic.pause(100)
basic.showString("1")
basic.pause(100)
basic.showString("0")
basic.forever(function () {
	
})
